rds:
  db:
    url: ddakdae-rds-ins.ci75bvjgjcvv.ap-northeast-2.rds.amazonaws.com:5432/ddakdae
    username: postgres
    password: ddakdae-test

spring:
  profiles:
    active: local

  webflux:
    hiddenmethod:
      filter:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://${rds.db.url}
    username:  ${rds.db.username}
    password: ${rds.db.password}

logging:
  level:
    org.springframework.r2dbc: DEBUG

debug: true

---

spring:
  profiles:
    active: prod



