spring:
  profiles:
    active: local

  r2dbc:
    username: postgres
    password: ddakdae-test
    url: r2dbc:postgresql://ddakdae-rds-ins.ci75bvjgjcvv.ap-northeast-2.rds.amazonaws.com:5432/ddakdae

  webflux:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG

debug: true

---

spring:
  profiles:
    active: prod



