rds:
  db:
    url: ddakdae-rds-instance.ci75bvjgjcvv.ap-northeast-2.rds.amazonaws.com
    port: 5432
    database: ddakdae
    username: postgres
    password: ddakdae-test

server:
  ec2:
    ip: 15.164.24.152
    port: 8080

spring:
  profiles:
    active: local

  webflux:
    hiddenmethod:
      filter:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://${rds.db.url}:${rds.db.port}/${rds.db.database}
    username:  ${rds.db.username}
    password: ${rds.db.password}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.r2dbc: DEBUG

---

spring:
  profiles:
    active: prod

# EC2 SSH 접속 :  ssh -i "ddakdae-pem.pem" ubuntu@ec2-15-164-24-152.ap-northeast-2.compute.amazonaws.com
# EC2 -> RDS 접속 : psql --host=ddakdae-rds-instance.ci75bvjgjcvv.ap-northeast-2.rds.amazonaws.com --port=5432 --username=postgres